import '../models/model_chat_item.dart';

class DataChatItem {
  static List<MChatItem> mChatItem = <MChatItem>[
    MChatItem(
      "https://upload.wikimedia.org/wikipedia/commons/thumb/"
          "3/38/Volleyball_game.jpg/250px-Volleyball_game.jpg",
      "Spongebob",
      "ayo",
      1,
      "Today",
    ),
    MChatItem(
      "https://upload.wikimedia.org/wikipedia/commons/thumb/"
          "3/38/Volleyball_game.jpg/250px-Volleyball_game.jpg",
      "Patrick",
      "gas",
      4,
      "Today",
    ),
    MChatItem(
      "https://upload.wikimedia.org/wikipedia/commons/thumb/"
          "3/38/Volleyball_game.jpg/250px-Volleyball_game.jpg",
      "Sendi",
      "pergi",
      5,
      "Today",
    ),
    MChatItem(
      "https://upload.wikimedia.org/wikipedia/commons/thumb/"
          "3/38/Volleyball_game.jpg/250px-Volleyball_game.jpg",
      "Ultraman",
      "ke",
      12,
      "Today",
    ),
    MChatItem(
      "https://upload.wikimedia.org/wikipedia/commons/thumb/"
          "3/38/Volleyball_game.jpg/250px-Volleyball_game.jpg",
      "Goku",
      "pasar",
      8,
      "Today",
    ),
    MChatItem(
      "https://upload.wikimedia.org/wikipedia/commons/thumb/"
          "3/38/Volleyball_game.jpg/250px-Volleyball_game.jpg",
      "Thomas",
      "malam",
      9,
      "Today",
    ),
    MChatItem(
      "https://upload.wikimedia.org/wikipedia/commons/thumb/"
          "3/38/Volleyball_game.jpg/250px-Volleyball_game.jpg",
      "Diana",
      "ini",
      3,
      "Today",
    ),
  ];
}
